plugins {
    id "com.android.application"
}

android {
    namespace "com.alppco.intermediatestock"
    compileSdk 35

    defaultConfig {
        applicationId "com.alppco.appgold"
        minSdk 24
        targetSdk 35
        versionCode 210
        versionName "2.1.0-security"
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.17.0"
}
