plugins {
    id "com.android.application"
}

android {
    namespace "com.alppco.intermediatestock"
    compileSdk 35

    defaultConfig {
        minSdk 24
        targetSdk 35
        versionCode 230
        versionName "2.3.0"
    }

    flavorDimensions "edition"
    productFlavors {
        staff {
            dimension "edition"
            applicationId "com.alppco.appgold"
            resValue "string", "app_name", "APP Gold"
        }
        manager {
            dimension "edition"
            applicationId "com.alppco.appgold.manager"
            resValue "string", "app_name", "APP Gold Manager"
        }
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    implementation "androidx.webkit:webkit:1.17.0"
}
